name: 'Configuration Manager'
type: module
description: 'Allows administrators to import and export configuration changes.'
package: Core
# version: VERSION
configure: config.sync

# Information added by Drupal.org packaging script on 2023-02-24
version: '10.0.2+115-dev'
project: 'drupal'
datestamp: 1677232754
