name: Testing site config
type: profile
description: 'Minimal profile for testing with default site config.'
# version: VERSION
hidden: true

# Information added by Drupal.org packaging script on 2023-02-24
version: '10.0.2+115-dev'
project: 'drupal'
datestamp: 1677232754
